spring:
  datasource:
    url: "jdbc:h2:mem:dev-base;INIT=RUNSCRIPT FROM 'classpath:sql/create.tutorialtestingdb.sql'"
    driver-class-name: "org.h2.Driver"
    username: "tanguy"
    password: "tanguy"
  h2.console:
    enabled: true
    path: /h2-console
    settings.trace: false
    settings.web-allow-others: true